import { Roboto } from "next/font/google";
import Header from "../components/layout/Header";
import "./globals.css";

const robotoSans = Roboto({
 
  subsets: ["latin"],
  weight: ['400', '700'],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${robotoSans}  `}
      >
        <main className="max-w-4xl mx-auto p-4">
           <Header />
        {children}
        <footer className="border-t border-gray-200 text-center p-8 mt-16">
      &copy; 2025 All rights reserved.
    </footer>
        </main>
        
    
        
      </body>
    </html>
  );
}
